features:
  # disable mob no tick damage
  disable_no_tick_damange: true

  animals:
    # reduce the spawn of animal by breeding. default set to 25% chance of spawning
    # setting this bellow 0 will remove any spawning form breeding
    # settings this above 1 will in a way disable the functionality
    reduce_spawn_from_breeding: 0.25

