main: lowbrain.library.main.LowbrainLibrary
name: LowbrainLibrary
version: 0.0.1
author: Lowbrain
description: Library containing multiple utilies for all my plugins
commands:
  lb:
    usage: /lb <cmd> <...args>